# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'

development:
  adapter: postgresql
  encoding: unicode
  database: marketingtracker_development
  pool: 5
  username: countries
  password: 
  template: template0

test: &TEST
  adapter: postgresql
  encoding: unicode
  database: marketingtracker_test
  pool: 5
  username: countries
  password: 
  template: template0

production:
  adapter: postgresql
  encoding: unicode
  database: marketingtracker_production
  pool: 5
  username: countries
  password: 
  template: template0
